apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-n2casolutions-com-tls
spec:
  secretName: k8s-n2casolutions-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commanName: k8s.n2casolutions.com
  dnsNames:
    - k8s.n2casolutions.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.n2casolutions.com 


